### ISSUE TITLE
Pages deployment is failing

### ISSUE THREAD

**Issue by williamd1k0** [williamd1k0/manga-plus-top40#12]
```js
Fetching artifact metadata for github-pages in run 7264712434
Creating Pages deployment with payload:
{
	"artifact_id": 1[12](https://github.com/williamd1k0/manga-plus-top40/actions/runs/7264712434/job/19792829809#step:11:13)4509045,
	"pages_build_version": "a490bca72bf835c3481ddb19f427b95ca56471c8",
	"oidc_token": "***"
}
Error: Creating Pages deployment failed
Error: HttpError: No artifact_url provided
    at /home/runner/work/_actions/actions/deploy-pages/v4/node_modules/@octokit/request/dist-node/index.js:124:1
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at createPagesDeployment (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/api-client.js:68:1)
    at Deployment.create (/home/runner/work/_actions/actions/deploy-pages/v4/src/internal/deployment.js:78:1)
    at main (/home/runner/work/_actions/actions/deploy-pages/v4/src/index.js:30:1)
Error: Error: Failed to create deployment (status: 400) with build version a490bca72bf835c3481ddb[19](https://github.com/williamd1k0/manga-plus-top40/actions/runs/7264712434/job/19792829809#step:11:20)f427b95ca56471c8. Responded with: No artifact_url provided
```

**Comment by williamd1k0** [comment]
Related: https://github.com/actions/deploy-pages/issues/284

**Comment by williamd1k0** [comment]
Fixed in https://github.com/actions/deploy-pages/releases/tag/v4.0.1
